scripted effect open_random_ad
    random_list = {
        1 = { set_variable = { random_img_var = 1 } }
        1 = { set_variable = { random_img_var = 2 } }
        1 = { set_variable = { random_img_var = 3 } }
        1 = { set_variable = { random_img_var = 4 } }
        1 = { set_variable = { random_img_var = 5 } }
        1 = { set_variable = { random_img_var = 6 } }
        1 = { set_variable = { random_img_var = 7 } }
        1 = { set_variable = { random_img_var = 8 } }
        1 = { set_variable = { random_img_var = 9 } }
        1 = { set_variable = { random_img_var = 10 } }
        1 = { set_variable = { random_img_var = 11 } }
        1 = { set_variable = { random_img_var = 12 } }
        1 = { set_variable = { random_img_var = 13 } }
        1 = { set_variable = { random_img_var = 14 } }
        1 = { set_variable = { random_img_var = 15 } }
        1 = { set_variable = { random_img_var = 16 } }
        1 = { set_variable = { random_img_var = 17 } }
        1 = { set_variable = { random_img_var = 18 } }
        1 = { set_variable = { random_img_var = 19 } }
        1 = { set_variable = { random_img_var = 20 } }
        1 = { set_variable = { random_img_var = 21 } }
        1 = { set_variable = { random_img_var = 22 } }
        1 = { set_variable = { random_img_var = 23 } }
        1 = { set_variable = { random_img_var = 24 } }
        1 = { set_variable = { random_img_var = 25 } }
        1 = { set_variable = { random_img_var = 26 } }
        1 = { set_variable = { random_img_var = 27 } }
        1 = { set_variable = { random_img_var = 28 } }
        1 = { set_variable = { random_img_var = 29 } }
        1 = { set_variable = { random_img_var = 30 } }
        1 = { set_variable = { random_img_var = 31 } }
        1 = { set_variable = { random_img_var = 32 } }
    }
    set_country_flag = open_ad1


scripted effect click_me_button_ad_effects
    clr_country_flag = open_ad1
    random_list = {
        1 = { country_event = { id = response.1 } }
        1 = { country_event = { id = response.2 } }
        1 = { country_event = { id = response.3 } }
        1 = { country_event = { id = response.4 } }
        1 = { country_event = { id = response.5 } }
    }