scripted effect shadow_company_attacks_chance
    random_list = {
        50 = {
            random_list = {
                1 = { news_event = { id = shadow_company_attacks.1 } }
                1 = { news_event = { id = shadow_company_attacks.2 } }
                1 = { news_event = { id = shadow_company_attacks.3 } }
                1 = { news_event = { id = shadow_company_attacks.4 } }
                1 = { news_event = { id = shadow_company_attacks.5 } }
                1 = { news_event = { id = shadow_company_attacks.6 } }
                1 = { news_event = { id = shadow_company_attacks.7 } }
                1 = { news_event = { id = shadow_company_attacks.8 } }
                1 = { news_event = { id = shadow_company_attacks.9 } }
                1 = { news_event = { id = shadow_company_attacks.10 } }
            }
        }
        50 = {
            #nothing, this time
        }
    }

scripted effect random_text
    random_list = {
        1 = { set_variable = { text = 1 } }
        1 = { set_variable = { text = 2 } }
        1 = { set_variable = { text = 3 } }
        1 = { set_variable = { text = 4 } }
        1 = { set_variable = { text = 5 } }
        1 = { set_variable = { text = 6 } }
        1 = { set_variable = { text = 7 } }
        1 = { set_variable = { text = 8 } }
        1 = { set_variable = { text = 9 } }
        1 = { set_variable = { text = 10 } }
        1 = { set_variable = { text = 11 } }
        1 = { set_variable = { text = 12 } }
        1 = { set_variable = { text = 13 } }
        1 = { set_variable = { text = 14 } }
        1 = { set_variable = { text = 15 } }
        1 = { set_variable = { text = 16 } }
        1 = { set_variable = { text = 17 } }
        1 = { set_variable = { text = 18 } }
        1 = { set_variable = { text = 19 } }
        1 = { set_variable = { text = 20 } }
        1 = { set_variable = { text = 21 } }
        1 = { set_variable = { text = 22 } }
        1 = { set_variable = { text = 23 } }
        1 = { set_variable = { text = 24 } }
        1 = { set_variable = { text = 25 } }
        1 = { set_variable = { text = 26 } }
        1 = { set_variable = { text = 27 } }
        1 = { set_variable = { text = 28 } }
        1 = { set_variable = { text = 29 } }
        1 = { set_variable = { text = 30 } }
        1 = { set_variable = { text = 31 } }
        1 = { set_variable = { text = 32 } }
        1 = { set_variable = { text = 33 } }
        1 = { set_variable = { text = 34 } }
        1 = { set_variable = { text = 35 } }
        1 = { set_variable = { text = 36 } }
        1 = { set_variable = { text = 37 } }
        1 = { set_variable = { text = 38 } }
        1 = { set_variable = { text = 39 } }
        1 = { set_variable = { text = 40 } }
        1 = { set_variable = { text = 41 } }
        1 = { set_variable = { text = 42 } }
        1 = { set_variable = { text = 43 } }
        1 = { set_variable = { text = 44 } }
        1 = { set_variable = { text = 45 } }
        1 = { set_variable = { text = 46 } }
        1 = { set_variable = { text = 47 } }
        1 = { set_variable = { text = 48 } }
        1 = { set_variable = { text = 49 } }
        1 = { set_variable = { text = 50 } }
        1 = { set_variable = { text = 51 } }
        1 = { set_variable = { text = 52 } }
        1 = { set_variable = { text = 53 } }
        1 = { set_variable = { text = 54 } }
        1 = { set_variable = { text = 55 } }
        1 = { set_variable = { text = 56 } }
        1 = { set_variable = { text = 57 } }
        1 = { set_variable = { text = 58 } }
        1 = { set_variable = { text = 59 } }
        1 = { set_variable = { text = 60 } }
        1 = { set_variable = { text = 61 } }
        1 = { set_variable = { text = 62 } }
        1 = { set_variable = { text = 63 } }
        1 = { set_variable = { text = 64 } }
        1 = { set_variable = { text = 65 } }
        1 = { set_variable = { text = 66 } }
        1 = { set_variable = { text = 67 } }
        1 = { set_variable = { text = 68 } }
        1 = { set_variable = { text = 69 } }
        1 = { set_variable = { text = 70 } }
        1 = { set_variable = { text = 71 } }
        1 = { set_variable = { text = 72 } }
        1 = { set_variable = { text = 73 } }
        1 = { set_variable = { text = 74 } }
        1 = { set_variable = { text = 75 } }
        1 = { set_variable = { text = 76 } }
        1 = { set_variable = { text = 77 } }
        1 = { set_variable = { text = 78 } }
        1 = { set_variable = { text = 79 } }
        1 = { set_variable = { text = 80 } }
        1 = { set_variable = { text = 81 } }
        1 = { set_variable = { text = 82 } }
        1 = { set_variable = { text = 83 } }
        1 = { set_variable = { text = 84 } }
        1 = { set_variable = { text = 85 } }
        1 = { set_variable = { text = 86 } }
        1 = { set_variable = { text = 87 } }
        1 = { set_variable = { text = 88 } }
        1 = { set_variable = { text = 89 } }
        1 = { set_variable = { text = 90 } }
        1 = { set_variable = { text = 91 } }
        1 = { set_variable = { text = 92 } }
        1 = { set_variable = { text = 93 } }
        1 = { set_variable = { text = 94 } }
        1 = { set_variable = { text = 95 } }
        1 = { set_variable = { text = 96 } }
        1 = { set_variable = { text = 97 } }
        1 = { set_variable = { text = 98 } }
        1 = { set_variable = { text = 99 } }
        1 = { set_variable = { text = 100 } }
        1 = { set_variable = { text = 101 } }
        1 = { set_variable = { text = 102 } }
        1 = { set_variable = { text = 103 } }
        1 = { set_variable = { text = 104 } }
        1 = { set_variable = { text = 105 } }
        1 = { set_variable = { text = 106 } }
        1 = { set_variable = { text = 107 } }
        1 = { set_variable = { text = 108 } }
        1 = { set_variable = { text = 109 } }
        1 = { set_variable = { text = 110 } }
        1 = { set_variable = { text = 111 } }
        1 = { set_variable = { text = 112 } }
        1 = { set_variable = { text = 113 } }
        1 = { set_variable = { text = 114 } }
        1 = { set_variable = { text = 115 } }
        1 = { set_variable = { text = 116 } }
        1 = { set_variable = { text = 117 } }
        1 = { set_variable = { text = 118 } }
        1 = { set_variable = { text = 119 } }
        1 = { set_variable = { text = 120 } }
        1 = { set_variable = { text = 121 } }
        1 = { set_variable = { text = 122 } }
        1 = { set_variable = { text = 123 } }
        1 = { set_variable = { text = 124 } }
        1 = { set_variable = { text = 125 } }
        1 = { set_variable = { text = 126 } }
        1 = { set_variable = { text = 127 } }
        1 = { set_variable = { text = 128 } }
        1 = { set_variable = { text = 129 } }
        1 = { set_variable = { text = 130 } }
        1 = { set_variable = { text = 131 } }
        1 = { set_variable = { text = 132 } }
        1 = { set_variable = { text = 133 } }
        1 = { set_variable = { text = 134 } }
        1 = { set_variable = { text = 135 } }
        1 = { set_variable = { text = 136 } }
        1 = { set_variable = { text = 137 } }
        1 = { set_variable = { text = 138 } }
        1 = { set_variable = { text = 139 } }
        1 = { set_variable = { text = 140 } }
        1 = { set_variable = { text = 141 } }
        1 = { set_variable = { text = 142 } }
        1 = { set_variable = { text = 143 } }
        1 = { set_variable = { text = 144 } }
        1 = { set_variable = { text = 145 } }
        1 = { set_variable = { text = 146 } }
        1 = { set_variable = { text = 147 } }
        1 = { set_variable = { text = 148 } }
        1 = { set_variable = { text = 149 } }
        1 = { set_variable = { text = 150 } }
        1 = { set_variable = { text = 151 } }
        1 = { set_variable = { text = 152 } }
        1 = { set_variable = { text = 153 } }
        1 = { set_variable = { text = 154 } }
        1 = { set_variable = { text = 155 } }
        1 = { set_variable = { text = 156 } }
        1 = { set_variable = { text = 157 } }
        1 = { set_variable = { text = 158 } }
        1 = { set_variable = { text = 159 } }
        1 = { set_variable = { text = 160 } }
        1 = { set_variable = { text = 161 } }
        1 = { set_variable = { text = 162 } }
        1 = { set_variable = { text = 163 } }
        1 = { set_variable = { text = 164 } }
        1 = { set_variable = { text = 165 } }
        1 = { set_variable = { text = 166 } }
        1 = { set_variable = { text = 167 } }
        1 = { set_variable = { text = 168 } }
        1 = { set_variable = { text = 169 } }
        1 = { set_variable = { text = 170 } }
        1 = { set_variable = { text = 171 } }
        1 = { set_variable = { text = 172 } }
        1 = { set_variable = { text = 173 } }
        1 = { set_variable = { text = 174 } }
        1 = { set_variable = { text = 175 } }
        1 = { set_variable = { text = 176 } }
        1 = { set_variable = { text = 177 } }
        1 = { set_variable = { text = 178 } }
        1 = { set_variable = { text = 179 } }
        1 = { set_variable = { text = 180 } }
        1 = { set_variable = { text = 181 } }
        1 = { set_variable = { text = 182 } }
        1 = { set_variable = { text = 183 } }
        1 = { set_variable = { text = 184 } }
        1 = { set_variable = { text = 185 } }
        1 = { set_variable = { text = 186 } }
        1 = { set_variable = { text = 187 } }
        1 = { set_variable = { text = 188 } }
        1 = { set_variable = { text = 189 } }
        1 = { set_variable = { text = 190 } }
        1 = { set_variable = { text = 191 } }
        1 = { set_variable = { text = 192 } }
        1 = { set_variable = { text = 193 } }
        1 = { set_variable = { text = 194 } }
        1 = { set_variable = { text = 195 } }
        1 = { set_variable = { text = 196 } }
        1 = { set_variable = { text = 197 } }
        1 = { set_variable = { text = 198 } }
        1 = { set_variable = { text = 199 } }
        1 = { set_variable = { text = 200 } }
        1 = { set_variable = { text = 201 } }
        1 = { set_variable = { text = 202 } }
        1 = { set_variable = { text = 203 } }
        1 = { set_variable = { text = 204 } }
        1 = { set_variable = { text = 205 } }
        1 = { set_variable = { text = 206 } }
        1 = { set_variable = { text = 207 } }
        1 = { set_variable = { text = 208 } }
        1 = { set_variable = { text = 209 } }
        1 = { set_variable = { text = 210 } }
        1 = { set_variable = { text = 211 } }
        1 = { set_variable = { text = 212 } }
        1 = { set_variable = { text = 213 } }
        1 = { set_variable = { text = 214 } }
        1 = { set_variable = { text = 215 } }
        1 = { set_variable = { text = 216 } }
        1 = { set_variable = { text = 217 } }
        1 = { set_variable = { text = 218 } }
        1 = { set_variable = { text = 219 } }
        1 = { set_variable = { text = 220 } }
    }



scripted effect lost_war_on_ads
    news_event = { id = lost_war_on_ads.1 }
scripted effect won_war_on_ads
    news_event = { id = won_war_on_ads.1 }
    # give country flag that won the war so none of the  stuff happen
on action
    on_monthly = {
        effect = {
            if
                is_ai = no
                not
                    has_country_flag = already_shown_the_result
                then
                
                    random_list = {
                        50 = { 
                            open_random_ad = yes 
                            shadow_company_attacks_chance = yes 
                        }
                        50 = {
                            # Lucky, This time
                        }
                    }
        }
    }
    on_daily = {
        effect = {
            if
                is_ai = no
                not
                    has_country_flag = already_shown_the_result
                then
                    if
                        has_country_flag = has_minigame
                        then
                            update_minigames = yes
                    if
                        check_variable = { breach_progress > 99 }
                        then
                            set_country_flag = already_shown_the_result
                            lost_war_on_ads = yes
                            # lost :(
                    else if
                        check_variable = { offense_bar > 99 }
                        then
                            set_country_flag = already_shown_the_result
                            won_war_on_ads = yes
                            # won :)
        }
    }
    on_startup = {
        effect = {
            every_country = {
                limit = {
                    is_ai = no
                }
                setup_mod = yes
            }
            
        }
    }

scripted effect setup_mod
    set_variable = { breach_progress = 0 }
    set_variable = { offense_bar = 0 }
    set_variable = { button_action = 0 }


scripted effect win_game
    set_variable = { offense_bar = 100 }
scripted effect loose_game
    set_variable = { breach_progress = 100 }
