# why is this called like this? there were plans to add more minigames but the realization of thats too much work hit in and the realization of feature creep.
scripted effect open_random_minigame
    # Option 1: Minigame 1
    set_country_flag = open_minigame_1

    # reset all buttons
    set_variable = { button1_enabled = 0 }
    set_variable = { button2_enabled = 0 }
    set_variable = { button3_enabled = 0 }
    set_variable = { button4_enabled = 0 }
    set_variable = { button5_enabled = 0 }
    set_variable = { button6_enabled = 0 }
    set_variable = { button7_enabled = 0 }
    set_variable = { button8_enabled = 0 }
    set_variable = { button9_enabled = 0 }
    set_variable = { button10_enabled = 0 }
    set_variable = { button11_enabled = 0 }
    set_variable = { button12_enabled = 0 }

    # Reset timer and progress bars
    set_variable = { time_left = 70 }
    set_variable = { done_in = 0 }
    set_country_flag = has_minigame
